################
#   AEconomy   #
################

# Explain:
# Asilux API can able to use a economy system customisable.
asilux-economy:
  # To enable/disable the Asilux Economy set the parameter to true/false.
  enable: true

  # Name of the money in the singular/plural
  name-singular: "ACoin"
  name-plural: "ACoins"

  # Symbole of the money
  symbol: "$"


###############
#    Redis    #
#   Manager   #
###############

# Explain:
# Asilux API use 2 redis database: Players account & Game-API database.
redis-manager:

  # Player account database credential
  players-account:
    ip: "localhost"
    password: ""
    port: 3306
    database: 1

  # Game-API database credential
  game-api:
    ip: "localhost"
    password: ""
    port: 3306
    database: 2

###############
#     SQL     #
#   Manager   #
###############

# Explain:
# Asilux API use one MySQL/SQL/SQLite/MariaDB database: Players account. (Recommended MySQL or SQL)
sql-manager:
  players-account:
    enable: true
    host: "localhost"
    username: "root"
    password: "root"
    port: 3306
    database: "players_account"